Convenient transforms to Infallible and back
ReactiveX/RxSwift pull request #2401
Opened 2022-02-14 14:22 UTC by asiliuk

Adds convenient `asInfallible()` to types that can't fail. And `asDriver()` to `InfallibleType`
Let me know if there is a better way to implement it than just assert on failure.
Ideal variant would be to do something similar to how `asDriver` is implemented, but there's no access `RxRelay` in `RxSwift` module and there's no access to `Infallible(_ source: Observable<Element>)` in `RxRelay` module

2022-03-26 21:58 UTC, freak4pc requested changes
Thank you! Idea seems good to me, just a few notes.

2022-03-26 21:58 UTC, freak4pc commented on RxCocoa/Traits/ControlEvent.swift
> +    }
```suggestion
    public func asInfallible() -> Infallible<Element> {
       asInfallible(onErrorFallbackTo: .empty())
    }
```

2022-03-26 21:58 UTC, freak4pc commented on RxCocoa/Traits/Driver/Infallible+Driver.swift
> +    }
I'd go for a single-liner here
```suggestion
    public func asDriver() -> Driver<Element> {
        SharedSequence(asObservable().observe(on: DriverSharingStrategy.scheduler))
    }
```

2022-03-26 21:58 UTC, freak4pc commented on RxCocoa/Traits/SharedSequence/SharedSequence.swift
> +        self.asInfallible { error in
like above

2022-03-26 21:58 UTC, freak4pc commented on RxRelay/BehaviorRelay.swift
> +        self.subject.asInfallible { error in
like above

2022-03-26 21:58 UTC, freak4pc commented on RxRelay/PublishRelay.swift
> +        self.subject.asInfallible { error in
like above

2022-03-30 04:37 UTC, freak4pc approved these changes
One note, I'll commit it and merge

2022-03-30 04:37 UTC, freak4pc commented on RxCocoa/Traits/Driver/Infallible+Driver.swift
> +        SharedSequence(asObservable().observe(on:DriverSharingStrategy.scheduler))
```suggestion
        SharedSequence(asObservable().observe(on: DriverSharingStrategy.scheduler))
```

2022-03-30 04:40 UTC, freak4pc commented
I think you need to run ./scripts/update-jazzy-config.rb (CI failed)

2022-03-30 07:14 UTC, asiliuk commented
Thanks for taking your time! Updated jazzy

2022-03-30 08:23 UTC, freak4pc commented
Failures seem unrelated. I'll merge, thank you!

2022-03-30 08:24 UTC, merged